insert into authors (id, first_name, last_name) values (1, 'Brendon', 'Knapman');
insert into authors (id, first_name, last_name) values (2, 'Eustace', 'Hardaway');
insert into authors (id, first_name, last_name) values (3, 'Ewen', 'Renvoys');
insert into authors (id, first_name, last_name) values (4, 'Pieter', 'Rushmere');
insert into authors (id, first_name, last_name) values (5, 'Candie', 'Youthed');
insert into authors (id, first_name, last_name) values (6, 'Gardy', 'Adamoli');
insert into authors (id, first_name, last_name) values (7, 'Efren', 'Whartonby');
insert into authors (id, first_name, last_name) values (8, 'Tedie', 'Waldram');
insert into authors (id, first_name, last_name) values (9, 'Nari', 'Barttrum');
insert into authors (id, first_name, last_name) values (10, 'Orel', 'Bridges');
insert into authors (id, first_name, last_name) values (11, 'Alard', 'De Ferrari');
insert into authors (id, first_name, last_name) values (12, 'Rudiger', 'Rehm');
insert into authors (id, first_name, last_name) values (13, 'Daren', 'Duke');
insert into authors (id, first_name, last_name) values (14, 'Casandra', 'Trigwell');
insert into authors (id, first_name, last_name) values (15, 'Petunia', 'Tregido');
insert into authors (id, first_name, last_name) values (16, 'Ardys', 'Aleksandrev');
insert into authors (id, first_name, last_name) values (17, 'Teodor', 'Patters');
insert into authors (id, first_name, last_name) values (18, 'Clarence', 'Teodori');
insert into authors (id, first_name, last_name) values (19, 'Ulrike', 'Larder');
insert into authors (id, first_name, last_name) values (20, 'Queenie', 'Challace');
insert into authors (id, first_name, last_name) values (21, 'Jecho', 'Blissett');


insert into books (id, price, price_old, title, author_id) values (1, 2660, 2306, 'Asoka', 4);
insert into books (id, price, price_old, title, author_id) values (2, 2961, 1485, 'Subin', 21);
insert into books (id, price, price_old, title, author_id) values (3, 2999, 1950, 'Kanlam', 8);
insert into books (id, price, price_old, title, author_id) values (4, 1841, 1490, 'Cardify', 7);
insert into books (id, price, price_old, title, author_id) values (5, 2842, 3457, 'Prodder', 18);
insert into books (id, price, price_old, title, author_id) values (6, 1954, 1032, 'Tresom', 20);
insert into books (id, price, price_old, title, author_id) values (7, 2889, 1578, 'Sonsing', 19);
insert into books (id, price, price_old, title, author_id) values (8, 1598, 3837, 'Quo Lux', 8);
insert into books (id, price, price_old, title, author_id) values (9, 843, 2047, 'Daltfresh', 12);
insert into books (id, price, price_old, title, author_id) values (10, 821, 1691, 'Bitchip', 12);
insert into books (id, price, price_old, title, author_id) values (11, 2154, 1985, 'Voyatouch', 17);
insert into books (id, price, price_old, title, author_id) values (12, 1821, 3828, 'Ronstring', 3);
insert into books (id, price, price_old, title, author_id) values (13, 1419, 1549, 'Fintone', 3);
insert into books (id, price, price_old, title, author_id) values (14, 2803, 3010, 'Bigtax', 16);
insert into books (id, price, price_old, title, author_id) values (15, 856, 3790, 'Namfix', 6);
insert into books (id, price, price_old, title, author_id) values (16, 1221, 3327, 'Transcof', 15);
insert into books (id, price, price_old, title, author_id) values (17, 2871, 2635, 'Duobam', 14);
insert into books (id, price, price_old, title, author_id) values (18, 1678, 3597, 'Veribet', 8);
insert into books (id, price, price_old, title, author_id) values (19, 1942, 2143, 'Domainer', 2);
insert into books (id, price, price_old, title, author_id) values (20, 1072, 1355, 'Tres-Zap', 5);
insert into books (id, price, price_old, title, author_id) values (21, 521, 3508, 'Tempsoft', 9);
