insert into books (author, title, priceOld, price) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, title, priceOld, price) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, title, priceOld, price) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, title, priceOld, price) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, title, priceOld, price) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, title, priceOld, price) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, title, priceOld, price) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, title, priceOld, price) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, title, priceOld, price) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, title, priceOld, price) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, title, priceOld, price) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, title, priceOld, price) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, title, priceOld, price) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, title, priceOld, price) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, title, priceOld, price) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, title, priceOld, price) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, title, priceOld, price) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, title, priceOld, price) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, title, priceOld, price) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, title, priceOld, price) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, title, priceOld, price) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, title, priceOld, price) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, title, priceOld, price) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, title, priceOld, price) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, title, priceOld, price) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');

insert into authors (author) values ('Абгарян Наринэ');
insert into authors (author) values ('Абдуллаев Чингиз');
insert into authors (author) values ('Аберкромби Джо');
insert into authors (author) values ('Авдич Оса');
insert into authors (author) values ('Адамович Алесь');
insert into authors (author) values ('Адамс Дуглас');
insert into authors (author) values ('Адра Фред');
insert into authors (author) values ('Азарова Екатерина');
insert into authors (author) values ('Азимов Айзек');
insert into authors (author) values ('Айленд Стоун Тамара');
insert into authors (author) values ('Акунин Борис');
insert into authors (author) values ('Алейникова Юлия');
insert into authors (author) values ('Александер Ллойд');
insert into authors (author) values ('Александрова Наталья');
insert into authors (author) values ('Алексеев Михаил');
insert into authors (author) values ('Алексеев Сергей');
insert into authors (author) values ('Аллан Пиз');
insert into authors (author) values ('Алфеева Лина');
insert into authors (author) values ('Альенде Исабель');
insert into authors (author) values ('Алюшина Татьяна');
insert into authors (author) values ('Амен Дэниел Грегори');
insert into authors (author) values ('Амирезвани Анита');
insert into authors (author) values ('Андерсон Джоди Линн');
insert into authors (author) values ('Андерсон Марина');
insert into authors (author) values ('Андерсон Сара М.');
insert into authors (author) values ('Анджелис Барбара де');
insert into authors (author) values ('Андреев Алексей');
insert into authors (author) values ('Андреева Марина');
insert into authors (author) values ('Андрижески Дж. С.');
insert into authors (author) values ('Андросенко Александр');
insert into authors (author) values ('Анжело Алекс');
insert into authors (author) values ('Аннандейл Дэвид');
insert into authors (author) values ('Антонова Наталия');
insert into authors (author) values ('Анхем Стефан');
insert into authors (author) values ('Арден Кэтрин');
insert into authors (author) values ('Ардова Алиса');
insert into authors (author) values ('Ариели Дэн');
insert into authors (author) values ('Арифуллина Елена');
insert into authors (author) values ('Арментроут Дженнифер Л.');
insert into authors (author) values ('Арментроут Дженнифер Ли');
insert into authors (author) values ('Арнольд Дэвид');
insert into authors (author) values ('Арсан Эммануэль');
insert into authors (author) values ('Арсеньева Елена');
insert into authors (author) values ('Арто Паасилинна');
insert into authors (author) values ('Архангельская Мария');
insert into authors (author) values ('Арье Вера');
insert into authors (author) values ('Астапов Максим');
insert into authors (author) values ('Астахов Павел');
insert into authors (author) values ('Аствацатуров Андрей');
insert into authors (author) values ('Атаманов Михаил');
insert into authors (author) values ('Афанасьев Александр');
insert into authors (author) values ('Ахерн Сесилия');
insert into authors (author) values ('Байбаков Иван');
insert into authors (author) values ('Байер Уильям');
insert into authors (author) values ('Бакиров Анвар');
insert into authors (author) values ('Бакман Фредрик');
insert into authors (author) values ('Баковец Михаил');
insert into authors (author) values ('Баксбаум Джулия');
insert into authors (author) values ('Бакстер Стивен');
insert into authors (author) values ('Бакулина Екатерина');
insert into authors (author) values ('Балахнин Алексей');
insert into authors (author) values ('Балдаччи Дэвид');
insert into authors (author) values ('Баллерини Луиджи');
insert into authors (author) values ('Баневич Артур');
insert into authors (author) values ('Банзл Питер');
insert into authors (author) values ('Баранова Ирина');
insert into authors (author) values ('Барбара Пиз');
insert into authors (author) values ('Барбери Мюриель');
insert into authors (author) values ('Барден Фил');
insert into authors (author) values ('Бардуго Лей');
insert into authors (author) values ('Баринова Любовь');
insert into authors (author) values ('Барисо Джастин');
insert into authors (author) values ('Баркер Клайв');
insert into authors (author) values ('Баркер Хейли');
insert into authors (author) values ('Бармин Егор');
insert into authors (author) values ('Барнетт Дэвид');
insert into authors (author) values ('Барр Эмили');
insert into authors (author) values ('Барридж Джей Джей');
insert into authors (author) values ('Баррон Томас Арчибальд');
insert into authors (author) values ('Барчок Михаэль');
insert into authors (author) values ('Баскова Ольга');
insert into authors (author) values ('Батлук Анна');
insert into authors (author) values ('Батуман Элиф');
insert into authors (author) values ('Батырев Максим');
insert into authors (author) values ('Батыршин Борис');
insert into authors (author) values ('Башибузук Александр');
insert into authors (author) values ('Беверли Элизабет');
insert into authors (author) values ('Бегбедер Фредерик');
insert into authors (author) values ('Беденко Иван');
insert into authors (author) values ('Безбашенный');
insert into authors (author) values ('Бейли Роберт');
insert into authors (author) values ('Бекетт Саймон');
insert into authors (author) values ('Белл Алекс');
insert into authors (author) values ('Белл Логан');
insert into authors (author) values ('Беллэрс Джон');
insert into authors (author) values ('Беляков Алексей');
insert into authors (author) values ('Беляков Анатолий');
insert into authors (author) values ('Белянин Андрей');
insert into authors (author) values ('Бен Иззи Джоэл');
insert into authors (author) values ('Бендер Алекс');
insert into authors (author) values ('Бенджамин Артур');
insert into authors (author) values ('Беннет Джули');
insert into authors (author) values ('Беннетт М. А.');
insert into authors (author) values ('Беннетт Роберт Джексон');
insert into authors (author) values ('Бердж Рейчел');
insert into authors (author) values ('Бернелл Марк');
insert into authors (author) values ('Бернетт Дин');
insert into authors (author) values ('Берри Джулия');
insert into authors (author) values ('Берроуз Уильям Сьюард');
insert into authors (author) values ('Берч Хизер');
insert into authors (author) values ('Беспалова Екатерина');
insert into authors (author) values ('Бехари Тереза');
insert into authors (author) values ('Беяз Кати');
insert into authors (author) values ('Билик Дмитрий');
insert into authors (author) values ('Бити Эрин');
insert into authors (author) values ('Блайтон Энид');
insert into authors (author) values ('Бланк Эль');
insert into authors (author) values ('Блинова Маргарита');
insert into authors (author) values ('Блэк Холли');
insert into authors (author) values ('Бове Клементина');
insert into authors (author) values ('Богатырёв Александр');
insert into authors (author) values ('Богушева Валерия');
insert into authors (author) values ('Бойн Джон');
insert into authors (author) values ('Боланд Шалини');
insert into authors (author) values ('Болд Эмили');
insert into authors (author) values ('Болдова Марина');
insert into authors (author) values ('Болл Джесси');
insert into authors (author) values ('Большаков Валерий');
insert into authors (author) values ('Бон Маша');
insert into authors (author) values ('Бонд Гвенда');
insert into authors (author) values ('Бор Алекс');
insert into authors (author) values ('Борисов Константин');
insert into authors (author) values ('Бородин Алексей');
insert into authors (author) values ('Боталова Мария');
insert into authors (author) values ('Боуэн Сарина');
insert into authors (author) values ('Боуэн Элизабет');
insert into authors (author) values ('Брайт Мэлоди Элен');
insert into authors (author) values ('Бракен Александра');
insert into authors (author) values ('Браун Дэн');
insert into authors (author) values ('Браун Кристофер');
insert into authors (author) values ('Брегман Питер');
insert into authors (author) values ('Бреннан Мари');
insert into authors (author) values ('Бреннан-Джобс Лиза');
insert into authors (author) values ('Бринкманн Каролина');
insert into authors (author) values ('Брокманн Нина');
insert into authors (author) values ('Броуди Джессика');
insert into authors (author) values ('Брук Ридиан');
insert into authors (author) values ('Брукс Терри');
insert into authors (author) values ('Брындза Роберт');
insert into authors (author) values ('Брэдбери Рэй');
insert into authors (author) values ('Брэдли Алан');
insert into authors (author) values ('Буджолд Лоис МакМастер');
insert into authors (author) values ('Бузин Максим');
insert into authors (author) values ('Буланов Константин');
insert into authors (author) values ('Булгаков Михаил');
insert into authors (author) values ('Булганова Елена');
insert into authors (author) values ('Бурмистров Денис');
insert into authors (author) values ('Бурмистрова Екатерина');
insert into authors (author) values ('Бут Карен');
insert into authors (author) values ('Бут Стивен');
insert into authors (author) values ('Буша Александр');
insert into authors (author) values ('Бушар Сандра');
insert into authors (author) values ('Бушков Александр');
insert into authors (author) values ('Бушковский Александр');
insert into authors (author) values ('Бушуева Мария');
insert into authors (author) values ('Быков Дмитрий');
insert into authors (author) values ('Бьюкес Лорен');
insert into authors (author) values ('Бэнкрофт Джосайя');
insert into authors (author) values ('Бэнкс Майя');
insert into authors (author) values ('Бэрд Жаклин');
insert into authors (author) values ('Бэрроуз Энни');
insert into authors (author) values ('Вайн Барбара');
insert into authors (author) values ('Вайнштейн Стелла');
insert into authors (author) values ('Вайцкин Джош');
insert into authors (author) values ('Валенте Кэтрин М.');
insert into authors (author) values ('Валентеева Ольга');
insert into authors (author) values ('Валериев Игорь');
insert into authors (author) values ('Валерия Вербинина');
insert into authors (author) values ('Ван Бой Саймон');
insert into authors (author) values ('Вапник Эмили');
insert into authors (author) values ('Варгас Фред');
insert into authors (author) values ('Варго Александр');
insert into authors (author) values ('Вардунас Игорь');
insert into authors (author) values ('Василенко Владимир');
insert into authors (author) values ('Васильев Александр');
insert into authors (author) values ('Васильев Андрей');
insert into authors (author) values ('Васина Екатерина');
insert into authors (author) values ('Васкес-Фигероа Альберто');
insert into authors (author) values ('Вафин Юрий');
insert into authors (author) values ('Вахненко Федор');
insert into authors (author) values ('Веббер Кэтрин');
insert into authors (author) values ('Вебер Бернард');
insert into authors (author) values ('Вега Даниэль');
insert into authors (author) values ('Вейр Энди');
insert into authors (author) values ('Веласкес-Манофф Мойзес');
insert into authors (author) values ('Велес Анна');
insert into authors (author) values ('Величко Андрей');
insert into authors (author) values ('Вентворт Патриция');
insert into authors (author) values ('Вербер Бернар');
insert into authors (author) values ('Вербинина Валерия');
insert into authors (author) values ('Вереснев Игорь');
insert into authors (author) values ('Веркин Эдуард');
insert into authors (author) values ('Верн Жюль');
insert into authors (author) values ('Верхова Екатерина');
insert into authors (author) values ('Весенняя Марина');
insert into authors (author) values ('Ветреная Инга');
insert into authors (author) values ('Вида Вендела');
insert into authors (author) values ('Винд Кристиан Роберт');
insert into authors (author) values ('Виндж Вернор Стеффан');
insert into authors (author) values ('Витгенштейн Людвиг');
insert into authors (author) values ('Вишневская Галина');
insert into authors (author) values ('Вишневский Януш');
insert into authors (author) values ('Владимиров Александр');
insert into authors (author) values ('Владимиров Денис');
insert into authors (author) values ('Водолазкин Евгений');
insert into authors (author) values ('Волгина Надежда');
insert into authors (author) values ('Волков Александр');
insert into authors (author) values ('Волков Тим');
insert into authors (author) values ('Волкова Светлана');
insert into authors (author) values ('Вольлебен Петер');
insert into authors (author) values ('Вольт Анастасия');
insert into authors (author) values ('Вольф Клаус-Петер');
insert into authors (author) values ('Воннегут Курт');
insert into authors (author) values ('Воронков Алексей');
insert into authors (author) values ('Воронова Мария');
insert into authors (author) values ('Воронцов Александр');
insert into authors (author) values ('Вострова Екатерина');
insert into authors (author) values ('Врочек Шимун');
insert into authors (author) values ('Вуд Алекс');
insert into authors (author) values ('Вуд Джосс');
insert into authors (author) values ('Вудворт Франциска');
insert into authors (author) values ('Вудфайн Кэтрин');
insert into authors (author) values ('Вулф Вирджиния');
insert into authors (author) values ('Вулф Терри');
insert into authors (author) values ('Вулф Тобиас');
insert into authors (author) values ('Выборнов Наиль');
insert into authors (author) values ('Выставной Владислав');
insert into authors (author) values ('Вязовский Алексей');
